# Generated by Django 4.0.3 on 2022-03-30 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wharehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='partymaterial',
            name='measure_type',
        ),
        migrations.AddField(
            model_name='material',
            name='measure_type',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Metr'), (3, 'Metr kvadrat'), (4, 'Soni')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(through='wharehouse.ProductMaterial', to='wharehouse.material'),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_material', to='wharehouse.material'),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_material', to='wharehouse.product'),
        ),
    ]
