# Generated by Django 4.0.3 on 2022-03-30 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wharehouse', '0002_productmaterial_remove_partymaterial_measure_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ('warehouse',)},
        ),
        migrations.AlterModelOptions(
            name='partymaterial',
            options={'ordering': ('material__name',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='productmaterial',
            options={'ordering': ('product__name', 'material__name')},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='party',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party', to='wharehouse.warehouse'),
        ),
    ]
