# Generated by Django 4.0.3 on 2022-03-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wharehouse', '0003_alter_material_options_alter_party_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partymaterial',
            old_name='warehouse',
            new_name='party',
        ),
    ]
