# Generated by Django 4.0.3 on 2022-03-30 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wharehouse', '0004_rename_warehouse_partymaterial_party'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ('-arrived_at',)},
        ),
    ]
