# Generated by Django 4.0.3 on 2022-03-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wharehouse', '0005_alter_party_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
