# Generated by Django 4.0.3 on 2022-03-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wharehouse', '0006_alter_product_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productmaterial',
            unique_together={('product', 'material')},
        ),
    ]
